import "@styles/globals.css";
import { Provider, Nav, Sidebar } from "@components";

export const metadata = {
  title: "Book Lens || Book data",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="xl:w-[1300px] m-auto overflow-hidden h-[100vh]">
            <Nav />
            <div className="flex gap-6 md:gap-20 ">
              <div className="h-[92vh] overflow-hidden xl:hover:overflow-auto">
                <Sidebar />
              </div>
              <div className="mt-4 flex flex-col gap-10 overflow-auto h-[88vh] videos flex-1">
                {children}
              </div>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
